### ISSUE TITLE
email validation: "example@example" returns an error

### ISSUE THREAD

**Issue by stationname** [python-validators/validators#293]
Like in the title: basically `a@a` shall be valid.
A "." is not necessary.

https://www.rfc-editor.org/rfc/rfc5322.html page 18 top.

**Comment by joe733** [comment]
Hi @stationname, `example@example` is validated when `simple_host = True`

```console
$ python -c "from validators import email; print(email('example@example', simple_host=True))"
True
```

The host-part validation call:

https://github.com/python-validators/validators/blob/9e94feea67d2787e984a100e1fb4642f5cd18288/src/validators/email.py#L80-L88

Simple host validation:

https://github.com/python-validators/validators/blob/9e94feea67d2787e984a100e1fb4642f5cd18288/src/validators/hostname.py#L24-L26

But `a@a` isn't validated because of the regex:

```re
^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]$
```

---

Here's a patch:

```patch
diff --git a/src/validators/hostname.py b/src/validators/hostname.py
index 4c7d609..b9dfbd5 100644
--- a/src/validators/hostname.py
+++ b/src/validators/hostname.py
@@ -23,7 +23,9 @@ def _port_regex():
 @lru_cache
 def _simple_hostname_regex():
     """Simple hostname validation regex."""
-    return re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]$")
+    # {0,59} because two characters are already matched at
+    # the beginning and at the end making the range {1, 61}
+    return re.compile(r"^(?!-)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,59}[a-zA-Z0-9])?(?<!-)$")
 
 
 def _port_validator(value: str):
```

PR is welcome.

**Comment by stationname** [comment]
❤️
